name: Check pull request

on: [push, pull_request]

jobs:
  testTSLint:
    runs-on: ubuntu-latest
    steps:
      - name: Initial dependencies
        run: npm install
      - name: Lint code
        run: ng lint
