name: Check pull request

on: [push, pull_request]

jobs:
  testTSLint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Initial Angular CLI
        run: npm install @angular/cli
      - name: Initial dependencies
        run: npm install
      - name: Lint code
        run: ng lint
